services:
  framework_core_fallbacks:
    class:  SumoCoders\FrameworkCoreBundle\Service\Fallbacks
    arguments: [%fallbacks%]

twig:
  debug:  %kernel.debug%
  strict_variables: %kernel.debug%
  globals:
    fallbacks: "@framework_core_fallbacks"

# Assetic Configuration
assetic:
    debug:  "%kernel.debug%"
    use_controller: false
    bundles:  [ SumoCodersFrameworkCoreBundle ]
    filters:
        less: ~
        sass: ~
        compass:
          images_dir: "%kernel.root_dir%/../vendor/sumocoders/framework-core-bundle/SumoCoders/FrameworkCoreBundle/Resources/assets/images"
          fonts_dir:  "%kernel.root_dir%/../vendor/sumocoders/framework-core-bundle//SumoCoders/FrameworkCoreBundle/Resources/public/fonts"
          http_fonts_path:  "../bundles/sumocodersframeworkcore/fonts"
          http_path:  /
          plugins:
            - compass_twitter_bootstrap
            - compass_sumo
        cssrewrite: ~
        coffee:
          bin:  /usr/local/bin/coffee
          node: /usr/local/bin/node
          apply_to: "\.coffee$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# I18n Configuration
jms_i18n_routing:
    default_locale: "%locale%"
    locales: ~
    strategy: prefix
