services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  framework.fallbacks:
    class:  SumoCoders\FrameworkCoreBundle\Service\Fallbacks
    arguments: ["%fallbacks%"]

  framework.jsdata:
    class: SumoCoders\FrameworkCoreBundle\Service\JsData
    arguments:
      - "@request_stack"

  framework.theme:
    class: SumoCoders\FrameworkCoreBundle\Service\Theme
    arguments:
      - "@request_stack"
      - "@framework.jsdata"
      - "@assets.packages"

  framework.menu_builder:
    class: SumoCoders\FrameworkCoreBundle\Menu\MenuBuilder
    calls:
      - [setFactory, ["@knp_menu.factory"]]
      - [setEventDispatcher, ["@event_dispatcher"]]
  framework.menu.main:
    class: Kpn\Menu\MenuItem
    factory: ["@framework.menu_builder", "createMainMenu"]
    arguments:
      - "@request_stack"
    tags:
      - { name: knp_menu.menu, alias: side_menu }

  SumoCoders\FrameworkCoreBundle\BreadCrumb\BreadCrumbBuilder:
    alias: framework.breadcrumb_builder

  framework.breadcrumb_builder:
    class: SumoCoders\FrameworkCoreBundle\BreadCrumb\BreadCrumbBuilder
    arguments:
      - "@request_stack"
      - "@knp_menu.factory"
      - "@event_dispatcher"

  framework.breadcrumb.main:
    class: Kpn\Menu\MenuItem
    factory: ["@framework.breadcrumb_builder", "createBreadCrumb"]
    arguments:
      - "@request_stack"
    tags:
      - { name: knp_menu.menu, alias: breadcrumb }

  framework.date_type_extension:
    class: SumoCoders\FrameworkCoreBundle\Form\Extension\DateTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }

  framework.time_type_extension:
    class: SumoCoders\FrameworkCoreBundle\Form\Extension\TimeTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TimeType }

  framework.date_time_type_extension:
    class: SumoCoders\FrameworkCoreBundle\Form\Extension\DateTimeTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateTimeType }

  framework.birthday_type_extension:
    class: SumoCoders\FrameworkCoreBundle\Form\Extension\BirthdayTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\BirthdayType }

  framework.button_type_icon_extension:
    class: SumoCoders\FrameworkCoreBundle\Form\Extension\ButtonTypeIconExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

  twig.framework_extension:
    class: SumoCoders\FrameworkCoreBundle\Twig\FrameworkExtension
    arguments:
      - "@service_container"
    tags:
      - { name: twig.extension }

  framework.response_securer:
    class: SumoCoders\FrameworkCoreBundle\EventListener\ResponseSecurer
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  SumoCoders\FrameworkCoreBundle\Mail\MessageFactory:
    arguments:
      - "@twig"
      - "%mailer.template%"
      - "%mailer.css_path%"
      - '%json_manifest_path%'
      - "%kernel.project_dir%/public"
    calls:
      - [setDefaultSender, ["%mailer.default_sender_email%", "%mailer.default_sender_name%"]]
      - [setDefaultReplyTo, ["%mailer.default_reply_to_email%", "%mailer.default_reply_to_name%"]]
      - [setDefaultTo, ["%mailer.default_to_email%", "%mailer.default_to_name%"]]

  sumocoders_form_type_date:
    class: SumoCoders\FrameworkCoreBundle\Form\Type\DateType
    tags:
      - { name: form.type, alias: sumoDate }

  sumocoders_form_type_fieldset:
    class: SumoCoders\FrameworkCoreBundle\Form\Type\FieldsetType
    arguments: []
    tags:
      - { name: form.type, alias: fieldset }

  sumocoders_form_type_image:
    class: SumoCoders\FrameworkCoreBundle\Form\Type\ImageType
    tags:
      - { name: form.type, alias: image }

  sumocoders_form_type_file:
    class: SumoCoders\FrameworkCoreBundle\Form\Type\FileType
    tags:
      - { name: form.type, alias: sumoFile }

  pagerfanta.view.sumocoders:
    class: SumoCoders\FrameworkCoreBundle\Twig\TwitterBootstrap3View
    public: false
    tags: [{ name: pagerfanta.view, alias: sumocoders }]
